### ISSUE TITLE
Acceptable use - visual branding guidelines

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/trademark_policy#4]
We haven't yet commissioned any branding work in terms of specific colors, logos, and typography, but once we have an updated identity, any acceptable use guidelines would need to take these into account.

Doing this would avoid confusion and reduce the chances of people being mislead about what is official or endorsed activity.

Mozilla and Opensearch have good examples:

https://opensearch.org/assets/brand/OpenSearch-Brand-Guide.pdf

https://www.mozilla.org/en-US/foundation/trademarks/policy/
https://mozilla.design/mozilla/logo-usage/
https://design.firefox.com/photon/visuals/product-identity-assets.html

## TODO

- [ ]  Create group for writing brief, what guidance we need
- [ ] Capture expected uses from group members
- [ ] Write brief
- [ ] Review and make next decisions

**Comment by mrchrisadams** [comment]
Some further context from the last call. See the meeting minutes:

> It was agreed that there will be a higher level company logo (maybe with a visual cue like being more colourful) that will be usable by steering members or ordinary members that meet the same preconditions as steering members (open members "should" comply with guidelines, these higher level members "must").

We now have access to a designer to work with:

> It was agreed that the trademark working group could consult the GSF logo designer on the above trademarks.

We'll still need some hands on deck to help get these fleshed out

**Comment by mrchrisadams** [comment]
During the last call, we decided it would make sense to write a brief as a google doc to share with the designer working on the GSF identity.

I've updated the issue accordingly.

**Comment by seanmcilroy29** [comment]
Paused until website is completed
